import type { ReactNode } from "react";

/**
 * Renders the small Markdown subset that PROJECT_CONTEXT.md sections use —
 * lists (one level of nesting), quotes, `**bold**`, `` `code` ``, whole-line
 * `_italic_` notes and `---` — as readable text instead of raw symbols.
 *
 * Deliberately not a general Markdown renderer: the input is generated by
 * LeanAI, and everything is built as React elements, so no HTML from the
 * project is ever injected into the page.
 */
export function MiniMarkdown({ text }: { text: string }) {
  const blocks: ReactNode[] = [];
  let list: { indent: number; text: string }[] = [];
  let quote: string[] = [];

  const flush = () => {
    if (list.length > 0) {
      const items = list;
      blocks.push(
        <ul key={`l${blocks.length}`} className="space-y-0.5">
          {items.map((item, index) => (
            <li
              key={index}
              className={`flex gap-1.5 ${item.indent > 0 ? "ml-4 text-ink-400" : "text-ink-300"}`}
            >
              <span aria-hidden className="text-ink-600">
                {item.indent > 0 ? "◦" : "•"}
              </span>
              <span className="min-w-0 break-words">{inline(item.text)}</span>
            </li>
          ))}
        </ul>,
      );
      list = [];
    }
    if (quote.length > 0) {
      blocks.push(
        <blockquote
          key={`q${blocks.length}`}
          className="border-l-2 border-ink-700 pl-2.5 text-ink-300 italic"
        >
          {inline(quote.join(" "))}
        </blockquote>,
      );
      quote = [];
    }
  };

  for (const raw of text.split("\n")) {
    const line = raw.trimEnd();
    const listItem = /^(\s*)- (.*)$/.exec(line);
    if (listItem) {
      if (quote.length > 0) flush();
      list.push({ indent: (listItem[1] ?? "").length >= 2 ? 1 : 0, text: listItem[2] ?? "" });
      continue;
    }
    if (line.startsWith(">")) {
      if (list.length > 0) flush();
      quote.push(line.replace(/^>\s?/, ""));
      continue;
    }
    flush();
    if (line.trim() === "") continue;
    if (line.trim() === "---") {
      blocks.push(<hr key={`h${blocks.length}`} className="border-ink-800" />);
    } else if (/^_[^_].*_$/.test(line.trim())) {
      blocks.push(
        <p key={`i${blocks.length}`} className="text-ink-500 italic">
          {inline(line.trim().slice(1, -1))}
        </p>,
      );
    } else if (line.startsWith("#")) {
      blocks.push(
        <p key={`t${blocks.length}`} className="font-semibold text-ink-200">
          {inline(line.replace(/^#+\s*/, ""))}
        </p>,
      );
    } else {
      blocks.push(
        <p key={`p${blocks.length}`} className="text-ink-300">
          {inline(line)}
        </p>,
      );
    }
  }
  flush();

  return <div className="space-y-2 text-[11px] leading-relaxed">{blocks}</div>;
}

/** `**bold**` and `` `code` ``; everything else stays plain text. */
function inline(text: string): ReactNode[] {
  return text
    .split(/(\*\*[^*]+\*\*|`[^`]+`)/g)
    .filter((part) => part !== "")
    .map((part, index) => {
      if (part.startsWith("**") && part.endsWith("**") && part.length > 4) {
        return (
          <strong key={index} className="font-semibold text-ink-200">
            {part.slice(2, -2)}
          </strong>
        );
      }
      if (part.startsWith("`") && part.endsWith("`") && part.length > 2) {
        return (
          <code
            key={index}
            className="mono rounded bg-ink-850 px-1 py-px text-[10.5px] text-ink-200"
          >
            {part.slice(1, -1)}
          </code>
        );
      }
      return part;
    });
}
